/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideLeftUp: typeof import('./src/components/AsideLeftUp.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ELementTree: typeof import('./src/components/ELementTree.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileFunction: typeof import('./src/components/BarFunction/FileFunction.vue')['default']
    Stage: typeof import('./src/components/MainStage/Stage.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
